### ISSUE TITLE
Scala 2.11 / Akka 2.3.6 artifact

### ISSUE THREAD

**Issue by AlexeyRaga** [sclasen/akka-kafka#20]
Hi Steve, 

Any chance to have a build for Scala 2.11 / Akka 2.3.6 on maven anytime soon?

Regards,
Alexey.

**Comment by kuhnen** [comment]
It works for me,  I believe you can close this ticket

**Comment by sclasen** [comment]
:+1:

**Comment by sclasen** [comment]
@AlexeyRaga @kuhnen  I just published `0.0.11-kafka-0.8.2.0-SNAPSHOT`  based on https://github.com/sclasen/akka-kafka/pull/30

If you have a chance let me know how it works

**Comment by kuhnen** [comment]
nice Scott,  I am little bit busy because I just got a new job and I am
moving to Germany :)  (I am from brazil by the way).
But I will try take a look at it  this weekend,..  thanks a lot


2015-02-03 20:21 GMT-02:00 Scott Clasen <notifications@github.com>:

**Comment by sclasen** [comment]
Thanks! no rush :)

**Comment by kuhnen** [comment]
Hello Scott,  I just tested the new version  and it is seems to be working
perfect :)
Thanks


2015-02-03 20:45 GMT-02:00 Scott Clasen <notifications@github.com>:
