### ISSUE TITLE
Question about state on the stream

### ISSUE THREAD

**Issue by richiesgr** [sclasen/akka-kafka#27]
Hi

Could you give me some help regarding the state that need to be used for the sync between my actor and yours.

StreamFSM.Processed = I've finished to process this message and must be sended back for each message.

But I can't use it because I receive the message in actor A process it in Actor B so could I use the StreamFSM.StartProcessing in A and send StreamFSM.Processed in B ?

Or is there other states that are relevant ?
Thanks

**Comment by kuhnen** [comment]
I believe what you need is
from inside ActorA

   ActorB forward !  message

then  ActorB will have the Stream sender as the sender()


2015-01-14 9:16 GMT-02:00 richiesgr <notifications@github.com>:

**Comment by sclasen** [comment]
@kuhnen you are correct, except no `!` needed just `ActorB forward message`

Thanks!

**Comment by sclasen** [comment]
pls reopen if any further questions/issues
