### ISSUE TITLE
Any reason for losing the key

### ISSUE THREAD

**Issue by radekg** [sclasen/akka-kafka#32]
Akka kafka seems to be passing the message only : https://github.com/sclasen/akka-kafka/blob/master/src/main/scala/com/sclasen/akka/kafka/Actors.scala#L203.
Is there a method to receive the key with a message?

**Comment by sclasen** [comment]
If you specify a msgHandler you can sent on the full msgandmetadata or do
an arbitrary transform.

The default handler does as you observed and just sends on the msg.

https://github.com/sclasen/akka-kafka/blob/master/src/main/scala/com/sclasen/akka/kafka/AkkaConsumer.scala#L149

https://github.com/sclasen/akka-kafka/blob/master/src/main/scala/com/sclasen/akka/kafka/Actors.scala#L200

**Comment by radekg** [comment]
Great stuff. Thank you.
