### ISSUE TITLE
Batch consumer priority

### ISSUE THREAD

**Issue by haritsE** [sclasen/akka-kafka#42]
Hello, 

Currently, I have several batch consumer running in my application. But some messages in certain batch consumer must be processed before messages in other batch consumer.
Is it possible to specify the priority of a batch consumer over the other? (e.g. process all message in this topic before other batch consumer process theirs)

**Comment by sclasen** [comment]
@haritsE thats not part of this library, but I assume that simply using a priorty mailbox on your reciever actor would do what you want? http://doc.akka.io/docs/akka/2.4.1/scala/mailboxes.html#PriorityMailbox

**Comment by haritsE** [comment]
Ah great, thanks @sclasen!
