### ISSUE TITLE
What exactly is outstanding?

### ISSUE THREAD

**Issue by artmoskvin** [sclasen/akka-kafka#57]
Can you please tell me what exactly outstanding means? Cause after some time of consuming I start receiving messages like: state=WaitingToSendBatch msg=StateTimeout outstanding=1 streams=8

**Comment by sclasen** [comment]
I believe it means that your reciever actor has not sent a `BatchConnectorFSM.BatchProcessed` for the previous batch, and as such the Batch Connector is holding on to the subsequent batch.

**Comment by artmoskvin** [comment]
@sclasen Got it. Thanks!
